# PrepBench - Copyright (c) 2026 Nimish Kanungo
# Licensed under the PolyForm Noncommercial License 1.0.0 (see LICENSE).
# Commercial use requires a separate licence from the copyright holder.

"""
Station C as a Databricks notebook (design §4.9, PRD P0-11).

Databricks source format: a `# Databricks notebook source` header, cells split by
`# COMMAND ----------`, SQL cells as `# MAGIC %sql`. The same dataset and the
same steps as the local engine, in the station's order, so the learner can repeat
the exercise on the real platform.

**Unverified until someone runs it.** The header and the first cell say so until
the pack's `notebook_verified_on` is set by hand, after a person has run the file
on Databricks Free Edition. We don't claim it works before that.
"""
from typing import List

from app.schemas.lab import LabPack
from app.services.lab import dataset_service

_SEP = "\n# COMMAND ----------\n\n"


def _md(*lines: str) -> str:
    return "\n".join(["# MAGIC %md", *[f"# MAGIC {line}".rstrip() for line in lines]])


def _sql(*lines: str) -> str:
    return "\n".join(["# MAGIC %sql", *[f"# MAGIC {line}".rstrip() for line in lines]])


def _spark_type(col_type: str) -> str:
    if col_type == "int64":
        return "BIGINT"
    if col_type == "float64":
        return "DOUBLE"
    if col_type.startswith("decimal("):
        return col_type.upper()
    if col_type == "timestamp":
        return "TIMESTAMP"
    if col_type == "timestamp_ntz":
        return "TIMESTAMP_NTZ"
    return "STRING"


def render(pack: LabPack, base_url: str = "http://localhost:8000") -> str:
    m = pack.manifest
    dataset = dataset_service.generate(pack)
    main_name = next(iter(pack.dataset.tables))
    main = dataset.tables[main_name]
    key = main.key
    schema = ", ".join(f"{c.name} {_spark_type(c.type)}" for c in main.spec.columns)
    cdc_schema = f"{schema}, op STRING"
    small = next((d for d in pack.dataset.defects if d.kind == "small_files"), None)
    drift = next((d for d in pack.dataset.defects if d.kind == "schema_drift" and d.table == main_name), None)
    ranges = [(b[0][key], b[-1][key]) for b in main.batches if b]
    download = f"{base_url}/api/v1/lab/lakehouse/packs/{m.id}/dataset"
    verified = m.notebook_verified_on
    status_line = (f"Verified on Databricks Free Edition on {verified}." if verified else
                   "UNVERIFIED: nobody has run this notebook on Databricks yet. Expect to fix things.")

    cells: List[str] = []
    cells.append("\n".join([
        "# Databricks notebook source",
        f"# Lakehouse Lab, Station C: {m.title} (fictional) -- pack {m.id} v{m.version}",
        f"# {status_line}",
        "# Generated by PrepBench. Every company, figure and person in this dataset is fictional.",
        "",
        _md(f"# Lakehouse Lab, Station C: the load that went wrong",
            "",
            f"**{status_line}**",
            "",
            "The same steps as PrepBench's local Delta engine, on Databricks. The data is fictional."),
    ]))
    cells.append(_md(
        "## 1. Put the dataset in a Volume",
        "",
        "1. In PrepBench, download the CSV files (the app must be running). Each downloads under the name used below:",
        f"   - `{download}/{main_name}.csv?copy=clean`",
        f"   - `{download}/{main_name}.csv?copy=legacy`",
        f"   - `{download}/{main_name}.csv?copy=cdc`",
        *([f"   - `{download}/{small.table}.csv?copy=clean`"] if small and small.table != main_name else []),
        "2. In Databricks, create a catalog schema and a Volume (Catalog > Create > Volume), e.g. `workspace.lakehouse_lab.raw`.",
        "3. Upload the files to the Volume, then set the path in the next cell.",
    ))
    cells.append("\n".join([
        'VOLUME = "/Volumes/workspace/lakehouse_lab/raw"   # where you uploaded the CSVs',
        'SCHEMA = "workspace.lakehouse_lab"',
        f'spark.sql(f"CREATE SCHEMA IF NOT EXISTS {{SCHEMA}}")',
        "",
        f'SCHEMA_DDL = "{schema}"',
        f'CDC_DDL = "{cdc_schema}"',
        "read = lambda name, ddl=SCHEMA_DDL: (spark.read.option(\"header\", True).schema(ddl).csv(f\"{VOLUME}/{name}\"))",
        f'clean = read("{main_name}.csv")',
        f'legacy = read("{main_name}_legacy.csv")',
        f'cdc = read("{main_name}_cdc.csv", CDC_DDL)',
    ]))
    lo, hi = ranges[0]
    cells.append("\n".join([
        f"# 2. Create the bronze table from batch 1 ({key} {lo}..{hi})",
        f'clean.where("{key} BETWEEN {lo} AND {hi}").write.format("delta").mode("overwrite").saveAsTable(f"{{SCHEMA}}.bronze_{main_name}")',
        f'display(spark.sql(f"SELECT COUNT(*) FROM {{SCHEMA}}.bronze_{main_name}"))',
    ]))
    if drift and len(ranges) >= drift.batch:
        dlo, dhi = ranges[drift.batch - 1]
        col = drift.add_column.name
        cells.append("\n".join([
            f"# 3. Batch {drift.batch} adds a column ({col}). Schema enforcement refuses it:",
            "from pyspark.sql import functions as F",
            f'drifted = clean.where("{key} BETWEEN {dlo} AND {dhi}").withColumn("{col}", F.lit("INSP-001"))  # placeholder values',
            "try:",
            f'    drifted.write.format("delta").mode("append").saveAsTable(f"{{SCHEMA}}.bronze_{main_name}")',
            "except Exception as e:",
            '    print("Refused, as expected:", str(e)[:300])',
        ]))
        cells.append("\n".join([
            "# 4. The same append with schema evolution",
            f'drifted.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(f"{{SCHEMA}}.bronze_{main_name}")',
        ]))
    if len(ranges) >= 2:
        rlo, rhi = ranges[1]
        cells.append("\n".join([
            f"# 5. Batch 2 arrives twice. A plain append duplicates it:",
            f'batch2 = clean.where("{key} BETWEEN {rlo} AND {rhi}")',
            f'batch2.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(f"{{SCHEMA}}.bronze_{main_name}")',
            f'batch2.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(f"{{SCHEMA}}.bronze_{main_name}")',
            f'display(spark.sql(f"SELECT COUNT(*) - COUNT(DISTINCT {key}) AS duplicate_rows FROM {{SCHEMA}}.bronze_{main_name}"))',
        ]))
    cells.append("\n".join([
        "# 6. MERGE the change batch (updates, deletes, inserts) on the key",
        'cdc.createOrReplaceTempView("cdc_batch")',
        "spark.sql(f\"\"\"",
        f"MERGE INTO {{SCHEMA}}.bronze_{main_name} AS t USING cdc_batch AS s ON t.{key} = s.{key}",
        "WHEN MATCHED AND s.op = 'D' THEN DELETE",
        "WHEN MATCHED AND s.op = 'U' THEN UPDATE SET *",
        "WHEN NOT MATCHED AND s.op = 'I' THEN INSERT *",
        '""")',
    ]))
    cells.append(_sql(
        "-- 7. History, time travel and restore",
        f"DESCRIBE HISTORY workspace.lakehouse_lab.bronze_{main_name};",
    ))
    cells.append(_sql(f"SELECT COUNT(*) FROM workspace.lakehouse_lab.bronze_{main_name} VERSION AS OF 0;"))
    cells.append(_sql(f"RESTORE TABLE workspace.lakehouse_lab.bronze_{main_name} TO VERSION AS OF 0;"))
    if small:
        cells.append("\n".join([
            f"# 8. Many small files: land {small.table} batch {small.batch} as {small.files} small writes, then compact",
            f'tel = read("{small.table}.csv", "{", ".join(f"{c.name} {_spark_type(c.type)}" for c in pack.dataset.tables[small.table].columns)}")',
            f'tel.repartition({small.files}).write.format("delta").mode("overwrite").saveAsTable(f"{{SCHEMA}}.bronze_{small.table}")',
            f'display(spark.sql(f"DESCRIBE DETAIL {{SCHEMA}}.bronze_{small.table}").select("numFiles"))',
        ]))
        cells.append(_sql(f"OPTIMIZE workspace.lakehouse_lab.bronze_{small.table} ZORDER BY (tool_id);"))
        cells.append(_sql(f"DESCRIBE DETAIL workspace.lakehouse_lab.bronze_{small.table};"))
    cells.append(_sql(
        "-- 9. Vacuum removes old files, and time travel to those versions stops working.",
        "-- Databricks refuses a retention under 7 days unless the check is turned off. Only do this on practice data.",
        "SET spark.databricks.delta.retentionDurationCheck.enabled = false;",
        f"VACUUM workspace.lakehouse_lab.bronze_{main_name} RETAIN 0 HOURS;",
    ))
    cells.append("\n".join([
        "# 10. Compare the legacy copy with the clean one: counts match, values don't",
        f'legacy.write.format("delta").mode("overwrite").saveAsTable(f"{{SCHEMA}}.legacy_{main_name}")',
        f'clean.write.format("delta").mode("overwrite").saveAsTable(f"{{SCHEMA}}.silver_{main_name}")',
        f'display(spark.sql(f"SELECT (SELECT COUNT(*) FROM {{SCHEMA}}.legacy_{main_name}) AS legacy_rows, (SELECT COUNT(*) FROM {{SCHEMA}}.silver_{main_name}) AS silver_rows"))',
    ]))
    compare_cols = [c for c in main.spec.columns if c.name != key]
    conditions = " OR ".join(f"NOT (l.{c.name} <=> r.{c.name})" for c in compare_cols)
    cells.append(_sql(
        "-- Rows whose values differ, joined on the business key",
        f"SELECT l.{key}, " + ", ".join(f"l.{c.name} AS legacy_{c.name}, r.{c.name} AS silver_{c.name}" for c in compare_cols),
        f"FROM workspace.lakehouse_lab.legacy_{main_name} l JOIN workspace.lakehouse_lab.silver_{main_name} r ON l.{key} = r.{key}",
        f"WHERE {conditions}",
        f"ORDER BY l.{key};",
    ))
    return _SEP.join(cells) + "\n"
