"""A small fictional document set (Northwind Data Platform). Every fact here is invented for the lesson."""

DOCS = [
    {"id": "leave-policy", "title": "Leave policy", "updated": "2026-03-01", "acl": "all",
     "text": "# Leave policy\n\n## Annual leave\nFull-time employees receive 24 days of paid annual leave per calendar year. Staff in their first six months receive 2 days per completed month. Unused days up to 5 may be carried into the next year.\n\n## Sick leave\nSick leave is paid for up to 10 days a year with a manager's note after 3 consecutive days."},
    {"id": "change-policy", "title": "Production change policy", "updated": "2026-06-12", "acl": "all",
     "text": "# Production change policy\n\n## Schema changes\nAny schema change to a production table needs written approval from the data owner and a second review from a platform engineer. Emergency changes may be applied first and reviewed within 24 hours.\n\n## Release windows\nProduction releases run Tuesday and Thursday between 10:00 and 15:00 UTC. No releases during quarter-end close."},
    {"id": "log-retention", "title": "Log retention standard", "updated": "2026-01-20", "acl": "all",
     "text": "# Log retention standard\n\n## Pipeline logs\nPipeline run logs are kept for 90 days in hot storage, then archived for 12 months. Audit logs for approved actions are kept for 7 years.\n\n## Debug traces\nDebug traces are deleted after 14 days and must not contain customer identifiers."},
    {"id": "runbook-errors", "title": "Runbook: common pipeline errors", "updated": "2026-08-30", "acl": "all",
     "text": "# Runbook: common pipeline errors\n\n## ERR-4417 schema drift\nERR-4417 means the incoming file has a column the target table does not. Check the source change log, then ask the data owner to approve a schema update. Do not drop the column silently.\n\n## ERR-5102 late arrival\nERR-5102 means the upstream file arrived after the 06:00 UTC cutoff. Rerun the job once the file lands; no manual fix is needed."},
    {"id": "runbook-freshness", "title": "Runbook: stale dashboard data", "updated": "2026-08-30", "acl": "all",
     "text": "# Runbook: stale dashboard data\n\nWhen a dashboard shows yesterday's numbers, first check the last successful run of the nightly refresh job. If the job succeeded but the numbers are old, the cache needs clearing. Escalate to the platform on-call if the refresh has failed twice in a row."},
    {"id": "access-policy", "title": "Data access policy", "updated": "2026-05-04", "acl": "all",
     "text": "# Data access policy\n\n## Requesting access\nAccess to a dataset is requested through the access portal and approved by the dataset's owner. Access is reviewed every 6 months and removed if unused for 90 days.\n\n## Contractors\nContractors get read-only access to non-sensitive datasets and must renew every 30 days."},
    {"id": "expenses", "title": "Travel and expenses", "updated": "2026-02-11", "acl": "all",
     "text": "# Travel and expenses\n\nEconomy class applies to flights under 6 hours. Hotel stays are capped at 180 dollars a night in major cities. Claims must be filed within 30 days with receipts attached."},
    {"id": "oncall", "title": "On-call guide", "updated": "2026-07-15", "acl": "all",
     "text": "# On-call guide\n\n## Rotation\nThe platform on-call rotates weekly on Mondays at 09:00 UTC. The primary responds to pages within 15 minutes; the secondary takes over after 30 minutes without acknowledgement.\n\n## Severity\nSeverity 1 means customer-facing data is wrong or unavailable. Severity 2 means a pipeline is failing but customers are not yet affected."},
    {"id": "finance-bonus", "title": "Finance bonus plan (restricted)", "updated": "2026-04-01", "acl": "finance",
     "text": "# Finance bonus plan\n\nThe annual bonus pool for the finance team is 8 percent of departmental budget, paid in March. Eligibility requires 6 months of service."},
    {"id": "leave-policy-2024", "title": "Leave policy (superseded 2024 version)", "updated": "2024-03-01", "acl": "all",
     "text": "# Leave policy (superseded)\n\n## Annual leave\nFull-time employees receive 20 days of paid annual leave per calendar year. Unused days cannot be carried over."},
    {"id": "naming", "title": "Table naming standard", "updated": "2026-03-22", "acl": "all",
     "text": "# Table naming standard\n\nTables use lowercase snake_case. Raw tables start with raw_, cleaned tables with clean_, and published tables with pub_. A table name must not contain a date."},
    {"id": "vendor", "title": "Vendor review", "updated": "2026-06-30", "acl": "all",
     "text": "# Vendor review\n\nAny new vendor that will process customer data needs a security review before a contract is signed. The review takes about 10 working days. Procurement tracks the status in the vendor register."},
    {"id": "parental-leave", "title": "Parental leave", "updated": "2026-03-01", "acl": "all",
     "text": "# Parental leave\n\nNew parents receive 16 weeks of paid parental leave, which can be taken in two blocks within the first year. Parental leave is separate from annual leave and sick leave."},
    {"id": "holidays", "title": "Public holiday calendar", "updated": "2026-01-05", "acl": "all",
     "text": "# Public holiday calendar\n\nThe company observes 11 public holidays in 2026. If a holiday falls on a weekend, the following Monday is a day off. Release windows are paused on public holidays."},
    {"id": "customer-retention", "title": "Customer data retention", "updated": "2026-02-02", "acl": "all",
     "text": "# Customer data retention\n\nCustomer records are kept for 6 years after the contract ends and then deleted. Deletion requests from customers are completed within 30 days and logged."},
    {"id": "incident-template", "title": "Incident review template", "updated": "2026-07-15", "acl": "all",
     "text": "# Incident review template\n\nEvery severity 1 incident needs a written review within 5 working days. The review lists the timeline, the cause, what was detected late, and the actions with owners."},
    {"id": "report-cutoffs", "title": "Report cutoff times", "updated": "2026-05-20", "acl": "all",
     "text": "# Report cutoff times\n\nFinance reports are cut off at 18:00 UTC on the last working day. Sales dashboards refresh nightly at 02:00 UTC and show data up to the previous midnight."},
    {"id": "contractor-onboarding", "title": "Contractor onboarding", "updated": "2026-04-18", "acl": "all",
     "text": "# Contractor onboarding\n\nContractors sign the confidentiality agreement on day one and receive a laptop within 3 working days. Their manager requests dataset access for them through the access portal."},
]

# (question, gold document id, text the right answer must contain). None, None: the documents do not contain the answer.
QUESTIONS = [
    ('How many days of paid annual leave do full-time staff get?', 'leave-policy', '24 days'),
    ('Can I take unused vacation days into next year?', 'leave-policy', 'up to 5'),
    ("Who has to approve a change to a production table's structure?", 'change-policy', 'data owner'),
    ('What days can we release to production?', 'change-policy', 'Tuesday and Thursday'),
    ('How long do we keep pipeline run logs?', 'log-retention', '90 days'),
    ('What does ERR-4417 mean?', 'runbook-errors', 'column the target table does not'),
    ('The file came in after the cutoff, what do I do?', 'runbook-errors', 'Rerun the job'),
    ("My dashboard shows yesterday's numbers", 'runbook-freshness', 'nightly refresh'),
    ('How often is access to a dataset reviewed?', 'access-policy', 'every 6 months'),
    ('How fast must the primary on-call respond to a page?', 'oncall', '15 minutes'),
    ('What counts as a severity 1 incident?', 'oncall', 'customer-facing data is wrong'),
    ('What is the hotel cap per night?', 'expenses', '180'),
    ('How should raw tables be named?', 'naming', 'raw_'),
    ('How long does a vendor security review take?', 'vendor', '10 working days'),
    ('How much time off do new joiners get in their first few months?', 'leave-policy', '2 days per completed month'),
    ('Who signs off on structure changes to live tables?', 'change-policy', 'data owner'),
    ('What happens if the upstream feed is late?', 'runbook-errors', 'Rerun the job'),
    ('Can contractors keep dataset access for as long as they like?', 'access-policy', 'renew every 30 days'),
    ('Is the old 20 day annual leave rule still current?', 'leave-policy', '24 days'),
    ('How soon must the incident write-up be done after a severity 1?', 'incident-template', '5 working days'),
    ('When is the sales dashboard refreshed?', 'report-cutoffs', '02:00 UTC'),
    ('How long are debug traces kept?', 'log-retention', '14 days'),
    ("What is the CEO's salary?", None, None),
    ('Which cloud region hosts the finance warehouse?', None, None),
    ('Do we have a policy on working from another country?', None, None),
]
