# PrepBench - Copyright (c) 2026 Nimish Kanungo
# Licensed under the PolyForm Noncommercial License 1.0.0 (see LICENSE).
# Commercial use requires a separate licence from the copyright holder.

import os
from typing import Optional
from pathlib import Path
from pydantic_settings import BaseSettings

BASE_DIR = Path(__file__).resolve().parent.parent.parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Where recorded answers are kept on disk. Overridable so the test suites can
# record into a throwaway folder: backend/data/recordings holds the learner's
# own voice recordings, which nothing automated should ever write beside.
RECORDINGS_DIR = Path(os.environ.get("PREPBENCH_RECORDINGS_DIR") or (DATA_DIR / "recordings"))

class Settings(BaseSettings):
    PROJECT_NAME: str = "PrepBench"
    VERSION: str = "1.0.0"
    API_V1_STR: str = "/api/v1"
    LOG_LEVEL: str = "DEBUG"
    
    # Optional Gemini API Key for Content Validation & Vector Embedding RAG
    GEMINI_API_KEY: Optional[str] = None

    # SQLite Database Configuration
    DATABASE_PATH: Path = DATA_DIR / "exam_simulator.db"
    SQLALCHEMY_DATABASE_URI: str = f"sqlite:///{DATABASE_PATH}"
    
    # Default Question Bank Path (falls back to the repo-local copy in app/data)
    DEFAULT_QUESTION_BANK_PATH: Path = BASE_DIR / "app" / "data" / "PSM_I_Question_Bank.json"

    # NOTE: exam defaults (passing percentage, duration, question count) are
    # deliberately NOT configured here. They live in the AppSettings row and
    # are editable from the Settings page, which is the single source of truth
    # the app actually reads. Env vars for them existed but nothing consumed
    # them, so setting one silently did nothing.

    class Config:
        case_sensitive = True
        env_file = str(BASE_DIR / ".env")

settings = Settings()

def recording_file(stored_path: str) -> Path:
    """The file a recording row points at, and never anything outside the folder.

    Every name in that column was generated by this server (a uuid4 and .webm),
    so this is a guard rather than a fix. But it is the one place two endpoints
    and the analysis service turn a stored string into a path they then read or
    delete, and "the row can only name a file in its own folder" is cheap to
    enforce and expensive to be wrong about.
    """
    root = RECORDINGS_DIR.resolve()
    path = (RECORDINGS_DIR / stored_path).resolve()
    if path != root and root not in path.parents:
        raise ValueError(f"Recording path {stored_path!r} is outside the recordings folder.")
    return path
